name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-backend:
    name: Build backend (.NET)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear

      - name: Setup NuGet auth for GitHub Packages
        run: |
          dotnet nuget remove source github || true
          dotnet nuget add source "https://nuget.pkg.github.com/IvanovaArina/index.json" \
            --name github \
            --username IvanovaArina \
            --password "${{ secrets.GH_PACKAGES_TOKEN }}" \
            --store-password-in-clear-text
      - name: Debug token
        run: |
          echo "Token length: ${#GH_PACKAGES_TOKEN}"
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Restore & build AuthService
        working-directory: services/AuthService
        run: |
          dotnet restore
          dotnet build -c Release --no-restore

      - name: Restore & build ProfileService
        working-directory: services/ProfileService
        run: |
          dotnet restore
          dotnet build -c Release --no-restore

      - name: Restore & build PortfolioService
        working-directory: services/PortfolioService
        run: |
          dotnet restore
          dotnet build -c Release --no-restore

      - name: Restore & build ImageService
        working-directory: services/ImageService
        run: |
          dotnet restore
          dotnet build -c Release --no-restore

      - name: Restore & build MainApi
        working-directory: services/MainApi/FreelancePlatformConnect.Api
        run: |
          dotnet restore
          dotnet build -c Release --no-restore

  build-frontend:
    name: Build frontend (React)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & build frontend
        working-directory: front/my-react-app
        run: |
          npm ci
          npm run build
